name: Constructor de APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Descargar Archivos
        uses: actions/checkout@v3

      - name: 2. Preparar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 3. Construir Proyecto
        run: |
          npm install
          npm run build --if-present

      - name: 4. Crear Contenedor Android
        run: |
          npm install @capacitor/core @capacitor/cli @capacitor/android
          npx cap init "Mi App" "com.zerklucio.app" --web-dir dist
          npx cap add android
          npx cap copy android
          cd android && ./gradlew assembleDebug

      - name: 5. Guardar APK Final
        uses: actions/upload-artifact@v3
        with:
          name: Mi-Aplicacion-Instalable
          path: android/app/build/outputs/apk/debug/app-debug.apk
